name: AWS Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/html/gallery-system/Frontend
            git config --global credential.helper store
            git config --global user.name "Ali-Al-Ahmad"
            git config --global user.email "ali.alahmad.cs@gmail.com"
            echo "https://${{ secrets.TOKEN }}@github.com" | sudo tee ~/.git-credentials > /dev/null
            sudo chmod 600 ~/.git-credentials
            sudo git pull origin main
            sudo npm install
            sudo npm run build
            sudo systemctl restart apache2
